development:
  container: dayhomes_staging
  username: jonmholt
  api_key: 288bc129beca52ce4818b58e1a8cdc51
  cdn_url: https://307be285b1e14e0417c2-25181be79b1f36ccdc7d3c4ce16785ec.ssl.cf1.rackcdn.com
  use_fog: false

test:
  container: dayhomes_staging
  username: jonmholt
  api_key: 288bc129beca52ce4818b58e1a8cdc51
  cdn_url: https://307be285b1e14e0417c2-25181be79b1f36ccdc7d3c4ce16785ec.ssl.cf1.rackcdn.com

staging:
  container: dayhomes_staging
  username: jonmholt
  api_key: 288bc129beca52ce4818b58e1a8cdc51
  cdn_url: https://307be285b1e14e0417c2-25181be79b1f36ccdc7d3c4ce16785ec.ssl.cf1.rackcdn.com
  rackspace_cdn_ssl: true
  servicenet: true
  use_fog: true

production:
  container: dayhomes_production
  username: jonmholt
  api_key: 288bc129beca52ce4818b58e1a8cdc51
  cdn_url: https://262fdb89a61cfb8b2887-11e3d3d0a1159f06aff28541e9c4b079.ssl.cf1.rackcdn.com
  rackspace_cdn_ssl: true
  servicenet: true
  use_fog: true

old_production:
  container: dayhomes_production
  username: markbennett
  api_key: cb2acd1348d1dccab9ba68ee1eb38229
  cdn_url: https://db21d474e9403503a093-97e12afbe63538dbb594efedc6220dd8.ssl.cf2.rackcdn.com
  region: ord